// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtoSpaMVC.Data;

namespace OtoSpaMVC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180804165418_ManyUsers")]
    partial class ManyUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("OtoSpaMVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new { Id = "admin_ID_123456789", AccessFailedCount = 0, ConcurrencyStamp = "5a35960e-6402-4197-aa89-c75d6d1a161d", Email = "admin@oto.spa", EmailConfirmed = false, LockoutEnabled = false, PasswordHash = "AQAAAAEAACcQAAAAELwE7EV9gebLj4XN4uMnQxGTPimkv3Me9hU1MvfGCvSJstUXhJdMHNqHSLfiJv9R2Q==", PhoneNumberConfirmed = false, TwoFactorEnabled = false, UserName = "admin" }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Editable");

                    b.Property<int>("Total");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Cart");

                    b.HasData(
                        new { ID = 13, Editable = true, Total = 2, UserID = "admin_ID_123456789" }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new { ID = 7, Name = "Car Accessories" },
                        new { ID = 8, Name = "Cleaning Products" }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.ContactUs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactHeader")
                        .HasMaxLength(160);

                    b.Property<string>("Content")
                        .HasMaxLength(160);

                    b.Property<bool>("Responded");

                    b.HasKey("ID");

                    b.ToTable("ContactUs");

                    b.HasData(
                        new { ID = 123, ContactHeader = "Hi", Content = "How Is Business Going?", Responded = false }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductName");

                    b.Property<double>("ProductPrice");

                    b.Property<string>("URIImage");

                    b.HasKey("ID");

                    b.ToTable("Product");

                    b.HasData(
                        new { ID = 1000, ProductName = "Prod_0", ProductPrice = 40482469.0 },
                        new { ID = 1001, ProductName = "Prod_1", ProductPrice = 138529631.0 },
                        new { ID = 1002, ProductName = "Prod_2", ProductPrice = 1425744914.0 },
                        new { ID = 1003, ProductName = "Prod_3", ProductPrice = 1096540113.0 },
                        new { ID = 1004, ProductName = "Prod_4", ProductPrice = 334869480.0 },
                        new { ID = 1005, ProductName = "Prod_5", ProductPrice = 1238624214.0 },
                        new { ID = 1006, ProductName = "Prod_6", ProductPrice = 1191703057.0 },
                        new { ID = 1007, ProductName = "Prod_7", ProductPrice = 2135376010.0 },
                        new { ID = 1008, ProductName = "Prod_8", ProductPrice = 1560131111.0 },
                        new { ID = 1009, ProductName = "Prod_9", ProductPrice = 561192084.0 },
                        new { ID = 1010, ProductName = "Prod_10", ProductPrice = 668672716.0 },
                        new { ID = 1011, ProductName = "Prod_11", ProductPrice = 1084829105.0 },
                        new { ID = 1012, ProductName = "Prod_12", ProductPrice = 1089556997.0 },
                        new { ID = 1013, ProductName = "Prod_13", ProductPrice = 311359140.0 },
                        new { ID = 1014, ProductName = "Prod_14", ProductPrice = 361341107.0 },
                        new { ID = 1015, ProductName = "Prod_15", ProductPrice = 930079981.0 },
                        new { ID = 1016, ProductName = "Prod_16", ProductPrice = 1750324715.0 },
                        new { ID = 1017, ProductName = "Prod_17", ProductPrice = 223811444.0 },
                        new { ID = 1018, ProductName = "Prod_18", ProductPrice = 483690787.0 },
                        new { ID = 1019, ProductName = "Prod_19", ProductPrice = 1566243559.0 },
                        new { ID = 1020, ProductName = "Prod_20", ProductPrice = 7824975.0 },
                        new { ID = 1021, ProductName = "Prod_21", ProductPrice = 441193677.0 },
                        new { ID = 1022, ProductName = "Prod_22", ProductPrice = 404983353.0 },
                        new { ID = 1023, ProductName = "Prod_23", ProductPrice = 384134101.0 },
                        new { ID = 1024, ProductName = "Prod_24", ProductPrice = 906951334.0 },
                        new { ID = 1025, ProductName = "Prod_25", ProductPrice = 1101017892.0 },
                        new { ID = 1026, ProductName = "Prod_26", ProductPrice = 1633276955.0 },
                        new { ID = 1027, ProductName = "Prod_27", ProductPrice = 974148078.0 },
                        new { ID = 1028, ProductName = "Prod_28", ProductPrice = 1189196742.0 },
                        new { ID = 1029, ProductName = "Prod_29", ProductPrice = 868404801.0 },
                        new { ID = 1030, ProductName = "Prod_30", ProductPrice = 1081744811.0 },
                        new { ID = 1031, ProductName = "Prod_31", ProductPrice = 273309575.0 },
                        new { ID = 1032, ProductName = "Prod_32", ProductPrice = 1127180086.0 },
                        new { ID = 1033, ProductName = "Prod_33", ProductPrice = 311692619.0 },
                        new { ID = 1034, ProductName = "Prod_34", ProductPrice = 731491632.0 },
                        new { ID = 1035, ProductName = "Prod_35", ProductPrice = 2055475856.0 },
                        new { ID = 1036, ProductName = "Prod_36", ProductPrice = 2014731808.0 },
                        new { ID = 1037, ProductName = "Prod_37", ProductPrice = 649921621.0 },
                        new { ID = 1038, ProductName = "Prod_38", ProductPrice = 1518906553.0 },
                        new { ID = 1039, ProductName = "Prod_39", ProductPrice = 2028299290.0 },
                        new { ID = 1040, ProductName = "Prod_40", ProductPrice = 51879952.0 },
                        new { ID = 1041, ProductName = "Prod_41", ProductPrice = 576199145.0 },
                        new { ID = 1042, ProductName = "Prod_42", ProductPrice = 1330246429.0 },
                        new { ID = 1043, ProductName = "Prod_43", ProductPrice = 784043249.0 },
                        new { ID = 1044, ProductName = "Prod_44", ProductPrice = 1773561559.0 },
                        new { ID = 1045, ProductName = "Prod_45", ProductPrice = 687332145.0 },
                        new { ID = 1046, ProductName = "Prod_46", ProductPrice = 1307222540.0 },
                        new { ID = 1047, ProductName = "Prod_47", ProductPrice = 680923046.0 },
                        new { ID = 1048, ProductName = "Prod_48", ProductPrice = 1880065049.0 },
                        new { ID = 1049, ProductName = "Prod_49", ProductPrice = 609820001.0 },
                        new { ID = 1050, ProductName = "Prod_50", ProductPrice = 903971180.0 },
                        new { ID = 1051, ProductName = "Prod_51", ProductPrice = 1150299668.0 },
                        new { ID = 1052, ProductName = "Prod_52", ProductPrice = 1263192468.0 },
                        new { ID = 1053, ProductName = "Prod_53", ProductPrice = 78984563.0 },
                        new { ID = 1054, ProductName = "Prod_54", ProductPrice = 1564596911.0 },
                        new { ID = 1055, ProductName = "Prod_55", ProductPrice = 1158884338.0 },
                        new { ID = 1056, ProductName = "Prod_56", ProductPrice = 1293141824.0 },
                        new { ID = 1057, ProductName = "Prod_57", ProductPrice = 453722712.0 },
                        new { ID = 1058, ProductName = "Prod_58", ProductPrice = 1749184325.0 },
                        new { ID = 1059, ProductName = "Prod_59", ProductPrice = 793447134.0 },
                        new { ID = 1060, ProductName = "Prod_60", ProductPrice = 1164942805.0 },
                        new { ID = 1061, ProductName = "Prod_61", ProductPrice = 1777150525.0 },
                        new { ID = 1062, ProductName = "Prod_62", ProductPrice = 358291167.0 },
                        new { ID = 1063, ProductName = "Prod_63", ProductPrice = 103838209.0 },
                        new { ID = 1064, ProductName = "Prod_64", ProductPrice = 1039042819.0 },
                        new { ID = 1065, ProductName = "Prod_65", ProductPrice = 1954958687.0 },
                        new { ID = 1066, ProductName = "Prod_66", ProductPrice = 1517244565.0 },
                        new { ID = 1067, ProductName = "Prod_67", ProductPrice = 189976277.0 },
                        new { ID = 1068, ProductName = "Prod_68", ProductPrice = 1139463054.0 },
                        new { ID = 1069, ProductName = "Prod_69", ProductPrice = 2012944444.0 },
                        new { ID = 1070, ProductName = "Prod_70", ProductPrice = 474943719.0 },
                        new { ID = 1071, ProductName = "Prod_71", ProductPrice = 512514993.0 },
                        new { ID = 1072, ProductName = "Prod_72", ProductPrice = 264500437.0 },
                        new { ID = 1073, ProductName = "Prod_73", ProductPrice = 14987043.0 },
                        new { ID = 1074, ProductName = "Prod_74", ProductPrice = 926475506.0 },
                        new { ID = 1075, ProductName = "Prod_75", ProductPrice = 991221376.0 },
                        new { ID = 1076, ProductName = "Prod_76", ProductPrice = 670542794.0 },
                        new { ID = 1077, ProductName = "Prod_77", ProductPrice = 1180535650.0 },
                        new { ID = 1078, ProductName = "Prod_78", ProductPrice = 170168088.0 },
                        new { ID = 1079, ProductName = "Prod_79", ProductPrice = 1779214735.0 },
                        new { ID = 1080, ProductName = "Prod_80", ProductPrice = 1353390898.0 },
                        new { ID = 1081, ProductName = "Prod_81", ProductPrice = 364465808.0 },
                        new { ID = 1082, ProductName = "Prod_82", ProductPrice = 653678575.0 },
                        new { ID = 1083, ProductName = "Prod_83", ProductPrice = 2138972287.0 },
                        new { ID = 1084, ProductName = "Prod_84", ProductPrice = 1524029167.0 },
                        new { ID = 1085, ProductName = "Prod_85", ProductPrice = 1491040689.0 },
                        new { ID = 1086, ProductName = "Prod_86", ProductPrice = 569712653.0 },
                        new { ID = 1087, ProductName = "Prod_87", ProductPrice = 460307422.0 },
                        new { ID = 1088, ProductName = "Prod_88", ProductPrice = 306691254.0 },
                        new { ID = 1089, ProductName = "Prod_89", ProductPrice = 1132202840.0 },
                        new { ID = 1090, ProductName = "Prod_90", ProductPrice = 174445931.0 },
                        new { ID = 1091, ProductName = "Prod_91", ProductPrice = 973120995.0 },
                        new { ID = 1092, ProductName = "Prod_92", ProductPrice = 460332842.0 },
                        new { ID = 1093, ProductName = "Prod_93", ProductPrice = 137571318.0 },
                        new { ID = 1094, ProductName = "Prod_94", ProductPrice = 275468384.0 },
                        new { ID = 1095, ProductName = "Prod_95", ProductPrice = 1981808620.0 },
                        new { ID = 1096, ProductName = "Prod_96", ProductPrice = 1777503524.0 },
                        new { ID = 1097, ProductName = "Prod_97", ProductPrice = 638520119.0 },
                        new { ID = 1098, ProductName = "Prod_98", ProductPrice = 1304595976.0 },
                        new { ID = 1099, ProductName = "Prod_99", ProductPrice = 1378198418.0 },
                        new { ID = 1100, ProductName = "Prod_100", ProductPrice = 729683126.0 },
                        new { ID = 1101, ProductName = "Prod_101", ProductPrice = 529358162.0 },
                        new { ID = 1102, ProductName = "Prod_102", ProductPrice = 1101055538.0 },
                        new { ID = 1103, ProductName = "Prod_103", ProductPrice = 1426716151.0 },
                        new { ID = 1104, ProductName = "Prod_104", ProductPrice = 1694471828.0 },
                        new { ID = 1105, ProductName = "Prod_105", ProductPrice = 1951051733.0 },
                        new { ID = 1106, ProductName = "Prod_106", ProductPrice = 297911130.0 },
                        new { ID = 1107, ProductName = "Prod_107", ProductPrice = 660317324.0 },
                        new { ID = 1108, ProductName = "Prod_108", ProductPrice = 712104603.0 },
                        new { ID = 1109, ProductName = "Prod_109", ProductPrice = 2132971081.0 },
                        new { ID = 1110, ProductName = "Prod_110", ProductPrice = 2047937090.0 },
                        new { ID = 1111, ProductName = "Prod_111", ProductPrice = 1672201720.0 },
                        new { ID = 1112, ProductName = "Prod_112", ProductPrice = 1843150170.0 },
                        new { ID = 1113, ProductName = "Prod_113", ProductPrice = 1529565136.0 },
                        new { ID = 1114, ProductName = "Prod_114", ProductPrice = 999651782.0 },
                        new { ID = 1115, ProductName = "Prod_115", ProductPrice = 212588896.0 },
                        new { ID = 1116, ProductName = "Prod_116", ProductPrice = 535583849.0 },
                        new { ID = 1117, ProductName = "Prod_117", ProductPrice = 1926398073.0 },
                        new { ID = 1118, ProductName = "Prod_118", ProductPrice = 139404588.0 },
                        new { ID = 1119, ProductName = "Prod_119", ProductPrice = 1107597676.0 },
                        new { ID = 1120, ProductName = "Prod_120", ProductPrice = 797357933.0 },
                        new { ID = 1121, ProductName = "Prod_121", ProductPrice = 469049042.0 },
                        new { ID = 1122, ProductName = "Prod_122", ProductPrice = 1442880569.0 },
                        new { ID = 1123, ProductName = "Prod_123", ProductPrice = 1566855760.0 },
                        new { ID = 1124, ProductName = "Prod_124", ProductPrice = 1250610412.0 },
                        new { ID = 1125, ProductName = "Prod_125", ProductPrice = 1061418270.0 },
                        new { ID = 1126, ProductName = "Prod_126", ProductPrice = 1611777697.0 },
                        new { ID = 1127, ProductName = "Prod_127", ProductPrice = 1686524665.0 },
                        new { ID = 1128, ProductName = "Prod_128", ProductPrice = 1299114205.0 },
                        new { ID = 1129, ProductName = "Prod_129", ProductPrice = 504262432.0 },
                        new { ID = 1130, ProductName = "Prod_130", ProductPrice = 773313398.0 },
                        new { ID = 1131, ProductName = "Prod_131", ProductPrice = 1591618221.0 },
                        new { ID = 1132, ProductName = "Prod_132", ProductPrice = 1435535220.0 },
                        new { ID = 1133, ProductName = "Prod_133", ProductPrice = 351565216.0 },
                        new { ID = 1134, ProductName = "Prod_134", ProductPrice = 461643508.0 },
                        new { ID = 1135, ProductName = "Prod_135", ProductPrice = 236144635.0 },
                        new { ID = 1136, ProductName = "Prod_136", ProductPrice = 823005816.0 },
                        new { ID = 1137, ProductName = "Prod_137", ProductPrice = 786557970.0 },
                        new { ID = 1138, ProductName = "Prod_138", ProductPrice = 2004096005.0 },
                        new { ID = 1139, ProductName = "Prod_139", ProductPrice = 1132572980.0 },
                        new { ID = 1140, ProductName = "Prod_140", ProductPrice = 605241458.0 },
                        new { ID = 1141, ProductName = "Prod_141", ProductPrice = 1468990875.0 },
                        new { ID = 1142, ProductName = "Prod_142", ProductPrice = 1307798365.0 },
                        new { ID = 1143, ProductName = "Prod_143", ProductPrice = 1880799366.0 },
                        new { ID = 1144, ProductName = "Prod_144", ProductPrice = 643861296.0 },
                        new { ID = 1145, ProductName = "Prod_145", ProductPrice = 61839757.0 },
                        new { ID = 1146, ProductName = "Prod_146", ProductPrice = 689566371.0 },
                        new { ID = 1147, ProductName = "Prod_147", ProductPrice = 490363252.0 },
                        new { ID = 1148, ProductName = "Prod_148", ProductPrice = 697515082.0 },
                        new { ID = 1149, ProductName = "Prod_149", ProductPrice = 1622475034.0 },
                        new { ID = 1150, ProductName = "Prod_150", ProductPrice = 858336670.0 },
                        new { ID = 1151, ProductName = "Prod_151", ProductPrice = 1410700997.0 },
                        new { ID = 1152, ProductName = "Prod_152", ProductPrice = 2058711077.0 },
                        new { ID = 1153, ProductName = "Prod_153", ProductPrice = 1756593846.0 },
                        new { ID = 1154, ProductName = "Prod_154", ProductPrice = 2140436031.0 },
                        new { ID = 1155, ProductName = "Prod_155", ProductPrice = 1820229630.0 },
                        new { ID = 1156, ProductName = "Prod_156", ProductPrice = 646073139.0 },
                        new { ID = 1157, ProductName = "Prod_157", ProductPrice = 1093795324.0 },
                        new { ID = 1158, ProductName = "Prod_158", ProductPrice = 1735701285.0 },
                        new { ID = 1159, ProductName = "Prod_159", ProductPrice = 45165457.0 },
                        new { ID = 1160, ProductName = "Prod_160", ProductPrice = 1898869582.0 },
                        new { ID = 1161, ProductName = "Prod_161", ProductPrice = 170982011.0 },
                        new { ID = 1162, ProductName = "Prod_162", ProductPrice = 920798665.0 },
                        new { ID = 1163, ProductName = "Prod_163", ProductPrice = 1767437717.0 },
                        new { ID = 1164, ProductName = "Prod_164", ProductPrice = 771769582.0 },
                        new { ID = 1165, ProductName = "Prod_165", ProductPrice = 2015914415.0 },
                        new { ID = 1166, ProductName = "Prod_166", ProductPrice = 1796262046.0 },
                        new { ID = 1167, ProductName = "Prod_167", ProductPrice = 903696853.0 },
                        new { ID = 1168, ProductName = "Prod_168", ProductPrice = 480033527.0 },
                        new { ID = 1169, ProductName = "Prod_169", ProductPrice = 175619046.0 },
                        new { ID = 1170, ProductName = "Prod_170", ProductPrice = 949178626.0 },
                        new { ID = 1171, ProductName = "Prod_171", ProductPrice = 1308621425.0 },
                        new { ID = 1172, ProductName = "Prod_172", ProductPrice = 1481897614.0 },
                        new { ID = 1173, ProductName = "Prod_173", ProductPrice = 566427154.0 },
                        new { ID = 1174, ProductName = "Prod_174", ProductPrice = 2061951764.0 },
                        new { ID = 1175, ProductName = "Prod_175", ProductPrice = 887962604.0 },
                        new { ID = 1176, ProductName = "Prod_176", ProductPrice = 720846223.0 },
                        new { ID = 1177, ProductName = "Prod_177", ProductPrice = 1121676749.0 },
                        new { ID = 1178, ProductName = "Prod_178", ProductPrice = 335106363.0 },
                        new { ID = 1179, ProductName = "Prod_179", ProductPrice = 600882554.0 },
                        new { ID = 1180, ProductName = "Prod_180", ProductPrice = 1931447445.0 },
                        new { ID = 1181, ProductName = "Prod_181", ProductPrice = 533526344.0 },
                        new { ID = 1182, ProductName = "Prod_182", ProductPrice = 401121482.0 },
                        new { ID = 1183, ProductName = "Prod_183", ProductPrice = 1236234717.0 },
                        new { ID = 1184, ProductName = "Prod_184", ProductPrice = 1205521308.0 },
                        new { ID = 1185, ProductName = "Prod_185", ProductPrice = 922207947.0 },
                        new { ID = 1186, ProductName = "Prod_186", ProductPrice = 1092502690.0 },
                        new { ID = 1187, ProductName = "Prod_187", ProductPrice = 1238536920.0 },
                        new { ID = 1188, ProductName = "Prod_188", ProductPrice = 1918208378.0 },
                        new { ID = 1189, ProductName = "Prod_189", ProductPrice = 201009424.0 },
                        new { ID = 1190, ProductName = "Prod_190", ProductPrice = 1149667042.0 },
                        new { ID = 1191, ProductName = "Prod_191", ProductPrice = 1288806038.0 },
                        new { ID = 1192, ProductName = "Prod_192", ProductPrice = 610452231.0 },
                        new { ID = 1193, ProductName = "Prod_193", ProductPrice = 1371042447.0 },
                        new { ID = 1194, ProductName = "Prod_194", ProductPrice = 793298944.0 },
                        new { ID = 1195, ProductName = "Prod_195", ProductPrice = 1993854993.0 },
                        new { ID = 1196, ProductName = "Prod_196", ProductPrice = 2107787756.0 },
                        new { ID = 1197, ProductName = "Prod_197", ProductPrice = 1099956194.0 },
                        new { ID = 1198, ProductName = "Prod_198", ProductPrice = 521141683.0 },
                        new { ID = 1199, ProductName = "Prod_199", ProductPrice = 187542427.0 },
                        new { ID = 1200, ProductName = "Prod_200", ProductPrice = 1972656904.0 },
                        new { ID = 1201, ProductName = "Prod_201", ProductPrice = 1345465064.0 },
                        new { ID = 1202, ProductName = "Prod_202", ProductPrice = 1569925271.0 },
                        new { ID = 1203, ProductName = "Prod_203", ProductPrice = 2081491582.0 },
                        new { ID = 1204, ProductName = "Prod_204", ProductPrice = 85408307.0 },
                        new { ID = 1205, ProductName = "Prod_205", ProductPrice = 1109310791.0 },
                        new { ID = 1206, ProductName = "Prod_206", ProductPrice = 1488398929.0 },
                        new { ID = 1207, ProductName = "Prod_207", ProductPrice = 904395822.0 },
                        new { ID = 1208, ProductName = "Prod_208", ProductPrice = 1254237628.0 },
                        new { ID = 1209, ProductName = "Prod_209", ProductPrice = 664585326.0 },
                        new { ID = 1210, ProductName = "Prod_210", ProductPrice = 511495306.0 },
                        new { ID = 1211, ProductName = "Prod_211", ProductPrice = 1083991936.0 },
                        new { ID = 1212, ProductName = "Prod_212", ProductPrice = 170800860.0 },
                        new { ID = 1213, ProductName = "Prod_213", ProductPrice = 546930630.0 },
                        new { ID = 1214, ProductName = "Prod_214", ProductPrice = 1820797205.0 },
                        new { ID = 1215, ProductName = "Prod_215", ProductPrice = 777455137.0 },
                        new { ID = 1216, ProductName = "Prod_216", ProductPrice = 1329456075.0 },
                        new { ID = 1217, ProductName = "Prod_217", ProductPrice = 1244159494.0 },
                        new { ID = 1218, ProductName = "Prod_218", ProductPrice = 2121511955.0 },
                        new { ID = 1219, ProductName = "Prod_219", ProductPrice = 1409157181.0 },
                        new { ID = 1220, ProductName = "Prod_220", ProductPrice = 335523624.0 },
                        new { ID = 1221, ProductName = "Prod_221", ProductPrice = 2117320672.0 },
                        new { ID = 1222, ProductName = "Prod_222", ProductPrice = 545084021.0 },
                        new { ID = 1223, ProductName = "Prod_223", ProductPrice = 1838619649.0 },
                        new { ID = 1224, ProductName = "Prod_224", ProductPrice = 585547550.0 },
                        new { ID = 1225, ProductName = "Prod_225", ProductPrice = 1219968134.0 },
                        new { ID = 1226, ProductName = "Prod_226", ProductPrice = 110281093.0 },
                        new { ID = 1227, ProductName = "Prod_227", ProductPrice = 1670450713.0 },
                        new { ID = 1228, ProductName = "Prod_228", ProductPrice = 1332723756.0 },
                        new { ID = 1229, ProductName = "Prod_229", ProductPrice = 1627692317.0 },
                        new { ID = 1230, ProductName = "Prod_230", ProductPrice = 339770394.0 },
                        new { ID = 1231, ProductName = "Prod_231", ProductPrice = 1180485575.0 },
                        new { ID = 1232, ProductName = "Prod_232", ProductPrice = 12646965.0 },
                        new { ID = 1233, ProductName = "Prod_233", ProductPrice = 1707159482.0 },
                        new { ID = 1234, ProductName = "Prod_234", ProductPrice = 187821196.0 },
                        new { ID = 1235, ProductName = "Prod_235", ProductPrice = 2145577927.0 },
                        new { ID = 1236, ProductName = "Prod_236", ProductPrice = 523196619.0 },
                        new { ID = 1237, ProductName = "Prod_237", ProductPrice = 2026709093.0 },
                        new { ID = 1238, ProductName = "Prod_238", ProductPrice = 562938309.0 },
                        new { ID = 1239, ProductName = "Prod_239", ProductPrice = 1655806063.0 },
                        new { ID = 1240, ProductName = "Prod_240", ProductPrice = 993404564.0 },
                        new { ID = 1241, ProductName = "Prod_241", ProductPrice = 1747702414.0 },
                        new { ID = 1242, ProductName = "Prod_242", ProductPrice = 1543894838.0 },
                        new { ID = 1243, ProductName = "Prod_243", ProductPrice = 665734951.0 },
                        new { ID = 1244, ProductName = "Prod_244", ProductPrice = 1249109664.0 },
                        new { ID = 1245, ProductName = "Prod_245", ProductPrice = 1625270652.0 },
                        new { ID = 1246, ProductName = "Prod_246", ProductPrice = 530117077.0 },
                        new { ID = 1247, ProductName = "Prod_247", ProductPrice = 1623117147.0 },
                        new { ID = 1248, ProductName = "Prod_248", ProductPrice = 1109840788.0 },
                        new { ID = 1249, ProductName = "Prod_249", ProductPrice = 1575439353.0 },
                        new { ID = 1250, ProductName = "Prod_250", ProductPrice = 76510817.0 },
                        new { ID = 1251, ProductName = "Prod_251", ProductPrice = 275740161.0 },
                        new { ID = 1252, ProductName = "Prod_252", ProductPrice = 538039785.0 },
                        new { ID = 1253, ProductName = "Prod_253", ProductPrice = 671580048.0 },
                        new { ID = 1254, ProductName = "Prod_254", ProductPrice = 1411614349.0 },
                        new { ID = 1255, ProductName = "Prod_255", ProductPrice = 1414931778.0 },
                        new { ID = 1256, ProductName = "Prod_256", ProductPrice = 212492942.0 },
                        new { ID = 1257, ProductName = "Prod_257", ProductPrice = 1290901168.0 },
                        new { ID = 1258, ProductName = "Prod_258", ProductPrice = 908055931.0 },
                        new { ID = 1259, ProductName = "Prod_259", ProductPrice = 425035719.0 },
                        new { ID = 1260, ProductName = "Prod_260", ProductPrice = 411141597.0 },
                        new { ID = 1261, ProductName = "Prod_261", ProductPrice = 1377543762.0 },
                        new { ID = 1262, ProductName = "Prod_262", ProductPrice = 1131267612.0 },
                        new { ID = 1263, ProductName = "Prod_263", ProductPrice = 1186140857.0 },
                        new { ID = 1264, ProductName = "Prod_264", ProductPrice = 1884410478.0 },
                        new { ID = 1265, ProductName = "Prod_265", ProductPrice = 890605277.0 },
                        new { ID = 1266, ProductName = "Prod_266", ProductPrice = 483456870.0 },
                        new { ID = 1267, ProductName = "Prod_267", ProductPrice = 23236924.0 },
                        new { ID = 1268, ProductName = "Prod_268", ProductPrice = 1918704980.0 },
                        new { ID = 1269, ProductName = "Prod_269", ProductPrice = 1234814824.0 },
                        new { ID = 1270, ProductName = "Prod_270", ProductPrice = 1813854064.0 },
                        new { ID = 1271, ProductName = "Prod_271", ProductPrice = 862342528.0 },
                        new { ID = 1272, ProductName = "Prod_272", ProductPrice = 93333084.0 },
                        new { ID = 1273, ProductName = "Prod_273", ProductPrice = 2025301438.0 },
                        new { ID = 1274, ProductName = "Prod_274", ProductPrice = 1975348163.0 },
                        new { ID = 1275, ProductName = "Prod_275", ProductPrice = 147416756.0 },
                        new { ID = 1276, ProductName = "Prod_276", ProductPrice = 2133021380.0 },
                        new { ID = 1277, ProductName = "Prod_277", ProductPrice = 1438944616.0 },
                        new { ID = 1278, ProductName = "Prod_278", ProductPrice = 1621884.0 },
                        new { ID = 1279, ProductName = "Prod_279", ProductPrice = 519872444.0 },
                        new { ID = 1280, ProductName = "Prod_280", ProductPrice = 101962956.0 },
                        new { ID = 1281, ProductName = "Prod_281", ProductPrice = 46759492.0 },
                        new { ID = 1282, ProductName = "Prod_282", ProductPrice = 2120205471.0 },
                        new { ID = 1283, ProductName = "Prod_283", ProductPrice = 1316879949.0 },
                        new { ID = 1284, ProductName = "Prod_284", ProductPrice = 963293399.0 },
                        new { ID = 1285, ProductName = "Prod_285", ProductPrice = 1623625779.0 },
                        new { ID = 1286, ProductName = "Prod_286", ProductPrice = 54557689.0 },
                        new { ID = 1287, ProductName = "Prod_287", ProductPrice = 900662463.0 },
                        new { ID = 1288, ProductName = "Prod_288", ProductPrice = 1855140679.0 },
                        new { ID = 1289, ProductName = "Prod_289", ProductPrice = 332484964.0 },
                        new { ID = 1290, ProductName = "Prod_290", ProductPrice = 1345196884.0 },
                        new { ID = 1291, ProductName = "Prod_291", ProductPrice = 791890997.0 },
                        new { ID = 1292, ProductName = "Prod_292", ProductPrice = 530765061.0 },
                        new { ID = 1293, ProductName = "Prod_293", ProductPrice = 1697498136.0 },
                        new { ID = 1294, ProductName = "Prod_294", ProductPrice = 656776365.0 },
                        new { ID = 1295, ProductName = "Prod_295", ProductPrice = 1175456348.0 },
                        new { ID = 1296, ProductName = "Prod_296", ProductPrice = 28546701.0 },
                        new { ID = 1297, ProductName = "Prod_297", ProductPrice = 1917349527.0 },
                        new { ID = 1298, ProductName = "Prod_298", ProductPrice = 340920019.0 },
                        new { ID = 1299, ProductName = "Prod_299", ProductPrice = 1918099933.0 },
                        new { ID = 1300, ProductName = "Prod_300", ProductPrice = 553925681.0 },
                        new { ID = 1301, ProductName = "Prod_301", ProductPrice = 2066475699.0 },
                        new { ID = 1302, ProductName = "Prod_302", ProductPrice = 1264007713.0 },
                        new { ID = 1303, ProductName = "Prod_303", ProductPrice = 1434621510.0 },
                        new { ID = 1304, ProductName = "Prod_304", ProductPrice = 1321180835.0 },
                        new { ID = 1305, ProductName = "Prod_305", ProductPrice = 773763835.0 },
                        new { ID = 1306, ProductName = "Prod_306", ProductPrice = 1742002623.0 },
                        new { ID = 1307, ProductName = "Prod_307", ProductPrice = 72333893.0 },
                        new { ID = 1308, ProductName = "Prod_308", ProductPrice = 255827431.0 },
                        new { ID = 1309, ProductName = "Prod_309", ProductPrice = 676309492.0 },
                        new { ID = 1310, ProductName = "Prod_310", ProductPrice = 841505944.0 },
                        new { ID = 1311, ProductName = "Prod_311", ProductPrice = 333143872.0 },
                        new { ID = 1312, ProductName = "Prod_312", ProductPrice = 701391183.0 },
                        new { ID = 1313, ProductName = "Prod_313", ProductPrice = 1947779033.0 },
                        new { ID = 1314, ProductName = "Prod_314", ProductPrice = 1882668309.0 },
                        new { ID = 1315, ProductName = "Prod_315", ProductPrice = 1923977651.0 },
                        new { ID = 1316, ProductName = "Prod_316", ProductPrice = 816933837.0 },
                        new { ID = 1317, ProductName = "Prod_317", ProductPrice = 1373983209.0 },
                        new { ID = 1318, ProductName = "Prod_318", ProductPrice = 1782443004.0 },
                        new { ID = 1319, ProductName = "Prod_319", ProductPrice = 1820380245.0 },
                        new { ID = 1320, ProductName = "Prod_320", ProductPrice = 248159487.0 },
                        new { ID = 1321, ProductName = "Prod_321", ProductPrice = 1142389953.0 },
                        new { ID = 1322, ProductName = "Prod_322", ProductPrice = 1875175438.0 },
                        new { ID = 1323, ProductName = "Prod_323", ProductPrice = 998331915.0 },
                        new { ID = 1324, ProductName = "Prod_324", ProductPrice = 1449213486.0 },
                        new { ID = 1325, ProductName = "Prod_325", ProductPrice = 434074966.0 },
                        new { ID = 1326, ProductName = "Prod_326", ProductPrice = 1891173013.0 },
                        new { ID = 1327, ProductName = "Prod_327", ProductPrice = 2102914141.0 },
                        new { ID = 1328, ProductName = "Prod_328", ProductPrice = 780636972.0 },
                        new { ID = 1329, ProductName = "Prod_329", ProductPrice = 212003714.0 },
                        new { ID = 1330, ProductName = "Prod_330", ProductPrice = 1678465601.0 },
                        new { ID = 1331, ProductName = "Prod_331", ProductPrice = 1775267399.0 },
                        new { ID = 1332, ProductName = "Prod_332", ProductPrice = 510136496.0 },
                        new { ID = 1333, ProductName = "Prod_333", ProductPrice = 1790601144.0 },
                        new { ID = 1334, ProductName = "Prod_334", ProductPrice = 1525542309.0 },
                        new { ID = 1335, ProductName = "Prod_335", ProductPrice = 1742566450.0 },
                        new { ID = 1336, ProductName = "Prod_336", ProductPrice = 342347325.0 },
                        new { ID = 1337, ProductName = "Prod_337", ProductPrice = 97695860.0 },
                        new { ID = 1338, ProductName = "Prod_338", ProductPrice = 1555294660.0 },
                        new { ID = 1339, ProductName = "Prod_339", ProductPrice = 1749125110.0 },
                        new { ID = 1340, ProductName = "Prod_340", ProductPrice = 1441218702.0 },
                        new { ID = 1341, ProductName = "Prod_341", ProductPrice = 1541819342.0 },
                        new { ID = 1342, ProductName = "Prod_342", ProductPrice = 56946931.0 },
                        new { ID = 1343, ProductName = "Prod_343", ProductPrice = 590943086.0 },
                        new { ID = 1344, ProductName = "Prod_344", ProductPrice = 1050574566.0 },
                        new { ID = 1345, ProductName = "Prod_345", ProductPrice = 424164911.0 },
                        new { ID = 1346, ProductName = "Prod_346", ProductPrice = 1650095360.0 },
                        new { ID = 1347, ProductName = "Prod_347", ProductPrice = 142581574.0 },
                        new { ID = 1348, ProductName = "Prod_348", ProductPrice = 1374425373.0 },
                        new { ID = 1349, ProductName = "Prod_349", ProductPrice = 292394260.0 },
                        new { ID = 1350, ProductName = "Prod_350", ProductPrice = 1918118057.0 },
                        new { ID = 1351, ProductName = "Prod_351", ProductPrice = 214159038.0 },
                        new { ID = 1352, ProductName = "Prod_352", ProductPrice = 1694502069.0 },
                        new { ID = 1353, ProductName = "Prod_353", ProductPrice = 80135320.0 },
                        new { ID = 1354, ProductName = "Prod_354", ProductPrice = 1082052345.0 },
                        new { ID = 1355, ProductName = "Prod_355", ProductPrice = 971131274.0 },
                        new { ID = 1356, ProductName = "Prod_356", ProductPrice = 1750895807.0 },
                        new { ID = 1357, ProductName = "Prod_357", ProductPrice = 1825271344.0 },
                        new { ID = 1358, ProductName = "Prod_358", ProductPrice = 1545003570.0 },
                        new { ID = 1359, ProductName = "Prod_359", ProductPrice = 299217768.0 },
                        new { ID = 1360, ProductName = "Prod_360", ProductPrice = 442186368.0 },
                        new { ID = 1361, ProductName = "Prod_361", ProductPrice = 1198684028.0 },
                        new { ID = 1362, ProductName = "Prod_362", ProductPrice = 851292467.0 },
                        new { ID = 1363, ProductName = "Prod_363", ProductPrice = 1603419263.0 },
                        new { ID = 1364, ProductName = "Prod_364", ProductPrice = 557439437.0 },
                        new { ID = 1365, ProductName = "Prod_365", ProductPrice = 625834091.0 },
                        new { ID = 1366, ProductName = "Prod_366", ProductPrice = 1382602922.0 },
                        new { ID = 1367, ProductName = "Prod_367", ProductPrice = 470385585.0 },
                        new { ID = 1368, ProductName = "Prod_368", ProductPrice = 1981832270.0 },
                        new { ID = 1369, ProductName = "Prod_369", ProductPrice = 1699697405.0 },
                        new { ID = 1370, ProductName = "Prod_370", ProductPrice = 993742225.0 },
                        new { ID = 1371, ProductName = "Prod_371", ProductPrice = 131349876.0 },
                        new { ID = 1372, ProductName = "Prod_372", ProductPrice = 1378284095.0 },
                        new { ID = 1373, ProductName = "Prod_373", ProductPrice = 1592913440.0 },
                        new { ID = 1374, ProductName = "Prod_374", ProductPrice = 1938757089.0 },
                        new { ID = 1375, ProductName = "Prod_375", ProductPrice = 265935691.0 },
                        new { ID = 1376, ProductName = "Prod_376", ProductPrice = 497554921.0 },
                        new { ID = 1377, ProductName = "Prod_377", ProductPrice = 696344251.0 },
                        new { ID = 1378, ProductName = "Prod_378", ProductPrice = 1507352895.0 },
                        new { ID = 1379, ProductName = "Prod_379", ProductPrice = 437160474.0 },
                        new { ID = 1380, ProductName = "Prod_380", ProductPrice = 343575152.0 },
                        new { ID = 1381, ProductName = "Prod_381", ProductPrice = 1160703338.0 },
                        new { ID = 1382, ProductName = "Prod_382", ProductPrice = 140600667.0 },
                        new { ID = 1383, ProductName = "Prod_383", ProductPrice = 2047838258.0 },
                        new { ID = 1384, ProductName = "Prod_384", ProductPrice = 2000964850.0 },
                        new { ID = 1385, ProductName = "Prod_385", ProductPrice = 876418462.0 },
                        new { ID = 1386, ProductName = "Prod_386", ProductPrice = 1640360876.0 },
                        new { ID = 1387, ProductName = "Prod_387", ProductPrice = 1989596722.0 },
                        new { ID = 1388, ProductName = "Prod_388", ProductPrice = 120660698.0 },
                        new { ID = 1389, ProductName = "Prod_389", ProductPrice = 2114006581.0 },
                        new { ID = 1390, ProductName = "Prod_390", ProductPrice = 1551266189.0 },
                        new { ID = 1391, ProductName = "Prod_391", ProductPrice = 76671527.0 },
                        new { ID = 1392, ProductName = "Prod_392", ProductPrice = 112287836.0 },
                        new { ID = 1393, ProductName = "Prod_393", ProductPrice = 668188791.0 },
                        new { ID = 1394, ProductName = "Prod_394", ProductPrice = 719050641.0 },
                        new { ID = 1395, ProductName = "Prod_395", ProductPrice = 1802130220.0 },
                        new { ID = 1396, ProductName = "Prod_396", ProductPrice = 102638774.0 },
                        new { ID = 1397, ProductName = "Prod_397", ProductPrice = 13123214.0 },
                        new { ID = 1398, ProductName = "Prod_398", ProductPrice = 1593099195.0 },
                        new { ID = 1399, ProductName = "Prod_399", ProductPrice = 1984336021.0 },
                        new { ID = 1400, ProductName = "Prod_400", ProductPrice = 601157535.0 },
                        new { ID = 1401, ProductName = "Prod_401", ProductPrice = 591821674.0 },
                        new { ID = 1402, ProductName = "Prod_402", ProductPrice = 1867828497.0 },
                        new { ID = 1403, ProductName = "Prod_403", ProductPrice = 1234323514.0 },
                        new { ID = 1404, ProductName = "Prod_404", ProductPrice = 858247581.0 },
                        new { ID = 1405, ProductName = "Prod_405", ProductPrice = 1198880080.0 },
                        new { ID = 1406, ProductName = "Prod_406", ProductPrice = 395470489.0 },
                        new { ID = 1407, ProductName = "Prod_407", ProductPrice = 1661184175.0 },
                        new { ID = 1408, ProductName = "Prod_408", ProductPrice = 1848457424.0 },
                        new { ID = 1409, ProductName = "Prod_409", ProductPrice = 228228553.0 },
                        new { ID = 1410, ProductName = "Prod_410", ProductPrice = 2033171899.0 },
                        new { ID = 1411, ProductName = "Prod_411", ProductPrice = 466663455.0 },
                        new { ID = 1412, ProductName = "Prod_412", ProductPrice = 1877513995.0 },
                        new { ID = 1413, ProductName = "Prod_413", ProductPrice = 519954995.0 },
                        new { ID = 1414, ProductName = "Prod_414", ProductPrice = 1515238162.0 },
                        new { ID = 1415, ProductName = "Prod_415", ProductPrice = 841078576.0 },
                        new { ID = 1416, ProductName = "Prod_416", ProductPrice = 470195260.0 },
                        new { ID = 1417, ProductName = "Prod_417", ProductPrice = 363049755.0 },
                        new { ID = 1418, ProductName = "Prod_418", ProductPrice = 1162049959.0 },
                        new { ID = 1419, ProductName = "Prod_419", ProductPrice = 1240616521.0 },
                        new { ID = 1420, ProductName = "Prod_420", ProductPrice = 545068761.0 },
                        new { ID = 1421, ProductName = "Prod_421", ProductPrice = 952601746.0 },
                        new { ID = 1422, ProductName = "Prod_422", ProductPrice = 1909320433.0 },
                        new { ID = 1423, ProductName = "Prod_423", ProductPrice = 1427421235.0 },
                        new { ID = 1424, ProductName = "Prod_424", ProductPrice = 1708026762.0 },
                        new { ID = 1425, ProductName = "Prod_425", ProductPrice = 329182597.0 },
                        new { ID = 1426, ProductName = "Prod_426", ProductPrice = 1578657586.0 },
                        new { ID = 1427, ProductName = "Prod_427", ProductPrice = 122207203.0 },
                        new { ID = 1428, ProductName = "Prod_428", ProductPrice = 285974698.0 },
                        new { ID = 1429, ProductName = "Prod_429", ProductPrice = 1696222415.0 },
                        new { ID = 1430, ProductName = "Prod_430", ProductPrice = 1722892463.0 },
                        new { ID = 1431, ProductName = "Prod_431", ProductPrice = 2044027253.0 },
                        new { ID = 1432, ProductName = "Prod_432", ProductPrice = 662840602.0 },
                        new { ID = 1433, ProductName = "Prod_433", ProductPrice = 1082612420.0 },
                        new { ID = 1434, ProductName = "Prod_434", ProductPrice = 1395598485.0 },
                        new { ID = 1435, ProductName = "Prod_435", ProductPrice = 1311349024.0 },
                        new { ID = 1436, ProductName = "Prod_436", ProductPrice = 852470387.0 },
                        new { ID = 1437, ProductName = "Prod_437", ProductPrice = 465872699.0 },
                        new { ID = 1438, ProductName = "Prod_438", ProductPrice = 601702576.0 },
                        new { ID = 1439, ProductName = "Prod_439", ProductPrice = 214196669.0 },
                        new { ID = 1440, ProductName = "Prod_440", ProductPrice = 2040543519.0 },
                        new { ID = 1441, ProductName = "Prod_441", ProductPrice = 1538772247.0 },
                        new { ID = 1442, ProductName = "Prod_442", ProductPrice = 1700734844.0 },
                        new { ID = 1443, ProductName = "Prod_443", ProductPrice = 1452027691.0 },
                        new { ID = 1444, ProductName = "Prod_444", ProductPrice = 1640430228.0 },
                        new { ID = 1445, ProductName = "Prod_445", ProductPrice = 496714633.0 },
                        new { ID = 1446, ProductName = "Prod_446", ProductPrice = 1906236725.0 },
                        new { ID = 1447, ProductName = "Prod_447", ProductPrice = 1151928387.0 },
                        new { ID = 1448, ProductName = "Prod_448", ProductPrice = 712546175.0 },
                        new { ID = 1449, ProductName = "Prod_449", ProductPrice = 1437567611.0 },
                        new { ID = 1450, ProductName = "Prod_450", ProductPrice = 744046859.0 },
                        new { ID = 1451, ProductName = "Prod_451", ProductPrice = 1299184565.0 },
                        new { ID = 1452, ProductName = "Prod_452", ProductPrice = 410668801.0 },
                        new { ID = 1453, ProductName = "Prod_453", ProductPrice = 1912078220.0 },
                        new { ID = 1454, ProductName = "Prod_454", ProductPrice = 851379159.0 },
                        new { ID = 1455, ProductName = "Prod_455", ProductPrice = 1208151335.0 },
                        new { ID = 1456, ProductName = "Prod_456", ProductPrice = 242096787.0 },
                        new { ID = 1457, ProductName = "Prod_457", ProductPrice = 2000002808.0 },
                        new { ID = 1458, ProductName = "Prod_458", ProductPrice = 1085892298.0 },
                        new { ID = 1459, ProductName = "Prod_459", ProductPrice = 2088660530.0 },
                        new { ID = 1460, ProductName = "Prod_460", ProductPrice = 1179818040.0 },
                        new { ID = 1461, ProductName = "Prod_461", ProductPrice = 1832858832.0 },
                        new { ID = 1462, ProductName = "Prod_462", ProductPrice = 787321376.0 },
                        new { ID = 1463, ProductName = "Prod_463", ProductPrice = 1711830555.0 },
                        new { ID = 1464, ProductName = "Prod_464", ProductPrice = 64931636.0 },
                        new { ID = 1465, ProductName = "Prod_465", ProductPrice = 1548740192.0 },
                        new { ID = 1466, ProductName = "Prod_466", ProductPrice = 1363418399.0 },
                        new { ID = 1467, ProductName = "Prod_467", ProductPrice = 207013474.0 },
                        new { ID = 1468, ProductName = "Prod_468", ProductPrice = 683952056.0 },
                        new { ID = 1469, ProductName = "Prod_469", ProductPrice = 1763484684.0 },
                        new { ID = 1470, ProductName = "Prod_470", ProductPrice = 1548203735.0 },
                        new { ID = 1471, ProductName = "Prod_471", ProductPrice = 1563918107.0 },
                        new { ID = 1472, ProductName = "Prod_472", ProductPrice = 1320942725.0 },
                        new { ID = 1473, ProductName = "Prod_473", ProductPrice = 359965189.0 },
                        new { ID = 1474, ProductName = "Prod_474", ProductPrice = 759668548.0 },
                        new { ID = 1475, ProductName = "Prod_475", ProductPrice = 565892060.0 },
                        new { ID = 1476, ProductName = "Prod_476", ProductPrice = 811462448.0 },
                        new { ID = 1477, ProductName = "Prod_477", ProductPrice = 2016888288.0 },
                        new { ID = 1478, ProductName = "Prod_478", ProductPrice = 1346586553.0 },
                        new { ID = 1479, ProductName = "Prod_479", ProductPrice = 623424028.0 },
                        new { ID = 1480, ProductName = "Prod_480", ProductPrice = 2130025065.0 },
                        new { ID = 1481, ProductName = "Prod_481", ProductPrice = 1986324745.0 },
                        new { ID = 1482, ProductName = "Prod_482", ProductPrice = 969256574.0 },
                        new { ID = 1483, ProductName = "Prod_483", ProductPrice = 408002633.0 },
                        new { ID = 1484, ProductName = "Prod_484", ProductPrice = 364287455.0 },
                        new { ID = 1485, ProductName = "Prod_485", ProductPrice = 1983303444.0 },
                        new { ID = 1486, ProductName = "Prod_486", ProductPrice = 1045470351.0 },
                        new { ID = 1487, ProductName = "Prod_487", ProductPrice = 310357928.0 },
                        new { ID = 1488, ProductName = "Prod_488", ProductPrice = 1790828807.0 },
                        new { ID = 1489, ProductName = "Prod_489", ProductPrice = 1747042696.0 },
                        new { ID = 1490, ProductName = "Prod_490", ProductPrice = 481364136.0 },
                        new { ID = 1491, ProductName = "Prod_491", ProductPrice = 412063125.0 },
                        new { ID = 1492, ProductName = "Prod_492", ProductPrice = 939575947.0 },
                        new { ID = 1493, ProductName = "Prod_493", ProductPrice = 72637592.0 },
                        new { ID = 1494, ProductName = "Prod_494", ProductPrice = 593974175.0 },
                        new { ID = 1495, ProductName = "Prod_495", ProductPrice = 1767280233.0 },
                        new { ID = 1496, ProductName = "Prod_496", ProductPrice = 163562770.0 },
                        new { ID = 1497, ProductName = "Prod_497", ProductPrice = 1548499835.0 },
                        new { ID = 1498, ProductName = "Prod_498", ProductPrice = 799207954.0 },
                        new { ID = 1499, ProductName = "Prod_499", ProductPrice = 1651285582.0 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Purchase", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartID");

                    b.Property<string>("CreditDetails");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("UserID");

                    b.ToTable("Purchase");

                    b.HasData(
                        new { ID = 15, CartID = 13, CreditDetails = "YOOOLLLLOOOO", UserID = "admin_ID_123456789" }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Rating", b =>
                {
                    b.Property<int>("ProductID");

                    b.Property<string>("UserID");

                    b.Property<int>("ID");

                    b.Property<int>("ProductRating");

                    b.HasKey("ProductID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("Rating");

                    b.HasData(
                        new { ProductID = 111, UserID = "admin_ID_123456789", ID = 16, ProductRating = 1 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.SeconderyModels.CartItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("CartID");

                    b.Property<int>("ProductID");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItem");

                    b.HasData(
                        new { ID = 14, Amount = 1, CartID = 13, ProductID = 111 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.SeconderyModels.ProductCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID");

                    b.Property<int>("ProductID");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new { ID = 17, CategoryID = 7, ProductID = 222 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.SeconderyModels.ProductSupplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductID");

                    b.Property<int>("SupplierID");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProductSupplier");

                    b.HasData(
                        new { ID = 18, ProductID = 111, SupplierID = 11 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Supplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Contact");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Website");

                    b.HasKey("ID");

                    b.ToTable("Supplier");

                    b.HasData(
                        new { ID = 11, Address = "lilach 99", Contact = "gil", Email = "gil@ziv.com", Name = "Guro", Phone = "054-9999999", Website = "www.anshubi.com" },
                        new { ID = 12, Address = "Aviv 99", Contact = "Zil", Email = "Ziv@Giv.com", Name = "Theuro", Phone = "054-9999199", Website = "www.tuna.com" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Cart", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Purchase", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Cart", "PurchaseCart")
                        .WithMany()
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Rating", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Product", "Product")
                        .WithMany("ProductRatings")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.ApplicationUser", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OtoSpaMVC.Models.SeconderyModels.CartItem", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OtoSpaMVC.Models.SeconderyModels.ProductCategory", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OtoSpaMVC.Models.SeconderyModels.ProductSupplier", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
