// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtoSpaMVC.Data;

namespace OtoSpaMVC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180818160144_nusefuck")]
    partial class nusefuck
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new { Id = "1", ConcurrencyStamp = "user", Name = "user", NormalizedName = "user" },
                        new { Id = "2", ConcurrencyStamp = "admin", Name = "admin", NormalizedName = "admin" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new { UserId = "admin_ID_123456789", RoleId = "2" },
                        new { UserId = "rt_7000", RoleId = "1" },
                        new { UserId = "rt_7001", RoleId = "1" },
                        new { UserId = "rt_7002", RoleId = "1" },
                        new { UserId = "rt_7003", RoleId = "1" },
                        new { UserId = "rt_7004", RoleId = "1" },
                        new { UserId = "rt_7005", RoleId = "1" },
                        new { UserId = "rt_7006", RoleId = "1" },
                        new { UserId = "rt_7007", RoleId = "1" },
                        new { UserId = "rt_7008", RoleId = "1" },
                        new { UserId = "rt_7009", RoleId = "1" },
                        new { UserId = "rt_7010", RoleId = "1" },
                        new { UserId = "rt_7011", RoleId = "1" },
                        new { UserId = "rt_7012", RoleId = "1" },
                        new { UserId = "rt_7013", RoleId = "1" },
                        new { UserId = "rt_7014", RoleId = "1" },
                        new { UserId = "rt_7015", RoleId = "1" },
                        new { UserId = "rt_7016", RoleId = "1" },
                        new { UserId = "rt_7017", RoleId = "1" },
                        new { UserId = "rt_7018", RoleId = "1" },
                        new { UserId = "rt_7019", RoleId = "1" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("OtoSpaMVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new { Id = "admin_ID_123456789", AccessFailedCount = 0, ConcurrencyStamp = "d08fd4ad-d0ec-4812-a17b-11a0f2a4f77c", Email = "admin@oto.spa", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "admin@oto.spa", NormalizedUserName = "admin@oto.spa", PasswordHash = "AQAAAAEAACcQAAAAEDVkvcxOR6a+IwcyDIS/yVX0HY88/JT7dfUN0iW5YOwViq7d9oWCp8a1y1K15VKehg==", PhoneNumberConfirmed = false, SecurityStamp = "admin@oto.spa", TwoFactorEnabled = false, UserName = "admin" },
                        new { Id = "rt_7000", AccessFailedCount = 0, ConcurrencyStamp = "97aca2f7-dfc3-4179-8673-9a67a3f3f83d", Email = "rt_7000@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7000@RaringsTest.com", NormalizedUserName = "rt_7000@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAECyMiH75YFjLf+JZk+Kqukmg9RzJPkchIUe2PCtOwQkgFD033fZtHd5BLug3K4gcSg==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7000@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7000" },
                        new { Id = "rt_7001", AccessFailedCount = 0, ConcurrencyStamp = "b361697c-23c7-47bb-8c9f-6f44365f7c8a", Email = "rt_7001@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7001@RaringsTest.com", NormalizedUserName = "rt_7001@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEOjBEjZ6zq9gGosCBozad602YoNgZBTjnN2lw7s4LR0svoCojACYjmV5Fp8yj3vWFg==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7001@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7001" },
                        new { Id = "rt_7002", AccessFailedCount = 0, ConcurrencyStamp = "bfca693e-4f35-466b-8c66-17bf03ef7d0f", Email = "rt_7002@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7002@RaringsTest.com", NormalizedUserName = "rt_7002@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAECe/QCly1yTp+0rRUtohz8O9CbhzvhAIjO+b6WdmSaBxUGZnSIeIMkoQz20JDdT/jQ==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7002@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7002" },
                        new { Id = "rt_7003", AccessFailedCount = 0, ConcurrencyStamp = "ba4db838-55f4-426b-b2fc-27402af65331", Email = "rt_7003@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7003@RaringsTest.com", NormalizedUserName = "rt_7003@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAELvuTBfLfAek/GAqhf7mRTide75k1RZYVEj/6o/5DwDEiECBYKm76Xo5OWNnzvu9Kg==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7003@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7003" },
                        new { Id = "rt_7004", AccessFailedCount = 0, ConcurrencyStamp = "387d0cea-3f98-4a37-ba07-bc9689833935", Email = "rt_7004@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7004@RaringsTest.com", NormalizedUserName = "rt_7004@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEKxfWvUVepD62gF/kRJpKub+/OHetclICnSOzk/7xsJkPEC8nigsVPnCTimGwjgHGA==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7004@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7004" },
                        new { Id = "rt_7005", AccessFailedCount = 0, ConcurrencyStamp = "ca21acaa-3ac3-4085-b39c-c547af3ac7b9", Email = "rt_7005@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7005@RaringsTest.com", NormalizedUserName = "rt_7005@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAECIKoaJYT0k1m0ui51iSsD4z5BOHAzULPiNNmokB6vQ1StQ4sFSABG22zZvWK1+qgg==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7005@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7005" },
                        new { Id = "rt_7006", AccessFailedCount = 0, ConcurrencyStamp = "96e945b1-ed59-4928-937e-e6e4e13bb396", Email = "rt_7006@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7006@RaringsTest.com", NormalizedUserName = "rt_7006@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEFU/lazC27RTEUuEjsekkii7Dqvp5AUeVVFgquRXzJtyiTmy3hl4byVzys/+s2P22A==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7006@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7006" },
                        new { Id = "rt_7007", AccessFailedCount = 0, ConcurrencyStamp = "e48a19fc-ce50-4384-9fef-bec541c77968", Email = "rt_7007@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7007@RaringsTest.com", NormalizedUserName = "rt_7007@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEOHNKyfVGc/NrxLqflrWhJTOEDI7jvCcue0Gx8k2JZmu8TGr+ZW6JJYV7Psy72gQXg==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7007@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7007" },
                        new { Id = "rt_7008", AccessFailedCount = 0, ConcurrencyStamp = "a7dd9a62-d2c7-463e-8cfa-2917ba61c4e4", Email = "rt_7008@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7008@RaringsTest.com", NormalizedUserName = "rt_7008@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEKOTbEA4w80LMnBPcT9kocQGrlTpdXSRD3+lmT28Bp57QPYH3S7rP7Hq7wAZY8Syzw==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7008@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7008" },
                        new { Id = "rt_7009", AccessFailedCount = 0, ConcurrencyStamp = "5c3af14f-ca26-482a-8d67-ea221f1379a0", Email = "rt_7009@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7009@RaringsTest.com", NormalizedUserName = "rt_7009@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAELl+JQ0aCbVgKK8mBOqPaw4EYOPYOEZyuYv1VnCpReNFlHaO5RtRKfx9Zzkigq790w==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7009@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7009" },
                        new { Id = "rt_7010", AccessFailedCount = 0, ConcurrencyStamp = "6bd60fd4-ba28-40a4-a7ff-1c6068bade05", Email = "rt_7010@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7010@RaringsTest.com", NormalizedUserName = "rt_7010@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEA3AWBP+jyVeHGda+lm5BPmr6IbWdoGCmfVPkf6a7ZiasnY6htiGGtHgyVSNzibQ0g==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7010@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7010" },
                        new { Id = "rt_7011", AccessFailedCount = 0, ConcurrencyStamp = "ff36ca7b-1383-43de-95b9-95d1ebefa6a2", Email = "rt_7011@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7011@RaringsTest.com", NormalizedUserName = "rt_7011@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEFr9dF3yJfly9hMKc4RXwvvangsA4qMgZq6JkeQag/Rc7a4lvvu5xijjAiNk3VCASQ==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7011@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7011" },
                        new { Id = "rt_7012", AccessFailedCount = 0, ConcurrencyStamp = "88021875-667d-4141-b779-8c51338356ab", Email = "rt_7012@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7012@RaringsTest.com", NormalizedUserName = "rt_7012@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAECYyOlZFcb6udIOiYDjwmsOsLQr3k3NyA31SrOPF9Xx8Za7KN/uZDxq5XnQH2nplDA==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7012@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7012" },
                        new { Id = "rt_7013", AccessFailedCount = 0, ConcurrencyStamp = "c8814d72-18d2-4aad-9863-f11b4de5c683", Email = "rt_7013@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7013@RaringsTest.com", NormalizedUserName = "rt_7013@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEMjgJKrs5orfo1vxCojq0vDf0RssxCaNRJcPfYJVyuJpEnBYMekeKQY47SyDwlAgvw==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7013@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7013" },
                        new { Id = "rt_7014", AccessFailedCount = 0, ConcurrencyStamp = "f7a4fb76-13a2-4065-b81b-e227da7ed97c", Email = "rt_7014@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7014@RaringsTest.com", NormalizedUserName = "rt_7014@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEGVxBok0Yt8dupDw2EroPSrZifGcaheGg2XUaml7c9TbGFFXSU8o43ASk4IchKwR1w==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7014@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7014" },
                        new { Id = "rt_7015", AccessFailedCount = 0, ConcurrencyStamp = "ab21d712-9feb-4142-a7c7-d30c0d0be317", Email = "rt_7015@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7015@RaringsTest.com", NormalizedUserName = "rt_7015@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEHVnbvP/SJ0aJIPzszdoP/wsNUJAthMZFh3qGUMlwZPWwVBMxd1oR7AHu7UbiKuSjQ==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7015@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7015" },
                        new { Id = "rt_7016", AccessFailedCount = 0, ConcurrencyStamp = "400bad82-7c17-45b0-a0f5-5c06551b92c7", Email = "rt_7016@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7016@RaringsTest.com", NormalizedUserName = "rt_7016@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEEJqjoopl3FzZXF5imsQJutmwq3oYP58yVD0uyXaWMY48yHlv7DPuy+hGduXHeO6lw==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7016@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7016" },
                        new { Id = "rt_7017", AccessFailedCount = 0, ConcurrencyStamp = "25dec285-6b07-436c-b7b5-190879f65af5", Email = "rt_7017@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7017@RaringsTest.com", NormalizedUserName = "rt_7017@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEBjTzbH8l/dV8evWJVxVQTUA+HaKkstxusG1i/gBXy/dbCTtFUGApjKCE7rZtX1pZw==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7017@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7017" },
                        new { Id = "rt_7018", AccessFailedCount = 0, ConcurrencyStamp = "89fdd403-455e-4412-9423-ae3abf7cd280", Email = "rt_7018@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7018@RaringsTest.com", NormalizedUserName = "rt_7018@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAECFnQsCZQYEMbd9QUav8KrKpSYyF6N3+SD6DeA6yeX/a3RCrWMnsOS7+CV+WWfGBiA==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7018@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7018" },
                        new { Id = "rt_7019", AccessFailedCount = 0, ConcurrencyStamp = "432cb2f1-8189-49f8-b892-a7d7bb48c058", Email = "rt_7019@RaringsTest.com", EmailConfirmed = true, LockoutEnabled = true, NormalizedEmail = "rt_7019@RaringsTest.com", NormalizedUserName = "rt_7019@RaringsTest.com", PasswordHash = "AQAAAAEAACcQAAAAEFb+Jv+oVHA4LvPIiLKfMyHG/bHKzWDYDKEbZcopz6LQqR+0yJbarsZ81et7Y1uBCQ==", PhoneNumberConfirmed = false, SecurityStamp = "rt_7019@RaringsTest.com", TwoFactorEnabled = false, UserName = "RaringsTest_rt_7019" }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Editable");

                    b.Property<int>("Total");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Cart");

                    b.HasData(
                        new { ID = 13, Editable = true, Total = 2, UserID = "admin_ID_123456789" }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.CartItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("CartID");

                    b.Property<int>("ProductID");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItem");

                    b.HasData(
                        new { ID = 14, Amount = 1, CartID = 13, ProductID = 111 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new { ID = 500, Name = "PrimeCategory_0" },
                        new { ID = 501, Name = "PrimeCategory_1" },
                        new { ID = 502, Name = "PrimeCategory_2" },
                        new { ID = 503, Name = "PrimeCategory_3" },
                        new { ID = 504, Name = "PrimeCategory_4" },
                        new { ID = 7, Name = "Car Accessories" },
                        new { ID = 8, Name = "Cleaning Products" }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.ContactUs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ContactDate");

                    b.Property<string>("ContactHeader")
                        .HasMaxLength(160);

                    b.Property<string>("ContactName")
                        .HasMaxLength(15);

                    b.Property<string>("Content")
                        .HasMaxLength(160);

                    b.Property<string>("Email")
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasMaxLength(15);

                    b.Property<bool>("Responded");

                    b.HasKey("ID");

                    b.ToTable("ContactUs");

                    b.HasData(
                        new { ID = 123, ContactDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), ContactHeader = "Hi", Content = "How Is Business Going?", Responded = false }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PrimaryCategoryID");

                    b.Property<string>("ProductName");

                    b.Property<double>("ProductPrice");

                    b.Property<string>("URIImage");

                    b.HasKey("ID");

                    b.HasIndex("PrimaryCategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new { ID = 1000, PrimaryCategoryID = 500, ProductName = "Prod_0", ProductPrice = 276.0 },
                        new { ID = 1001, PrimaryCategoryID = 501, ProductName = "Prod_1", ProductPrice = 184.0 },
                        new { ID = 1002, PrimaryCategoryID = 502, ProductName = "Prod_2", ProductPrice = 357.0 },
                        new { ID = 1003, PrimaryCategoryID = 503, ProductName = "Prod_3", ProductPrice = 104.0 },
                        new { ID = 1004, PrimaryCategoryID = 504, ProductName = "Prod_4", ProductPrice = 80.0 },
                        new { ID = 1005, PrimaryCategoryID = 500, ProductName = "Prod_5", ProductPrice = 344.0 },
                        new { ID = 1006, PrimaryCategoryID = 501, ProductName = "Prod_6", ProductPrice = 470.0 },
                        new { ID = 1007, PrimaryCategoryID = 502, ProductName = "Prod_7", ProductPrice = 288.0 },
                        new { ID = 1008, PrimaryCategoryID = 503, ProductName = "Prod_8", ProductPrice = 340.0 },
                        new { ID = 1009, PrimaryCategoryID = 504, ProductName = "Prod_9", ProductPrice = 49.0 },
                        new { ID = 1010, PrimaryCategoryID = 500, ProductName = "Prod_10", ProductPrice = 267.0 },
                        new { ID = 1011, PrimaryCategoryID = 501, ProductName = "Prod_11", ProductPrice = 138.0 },
                        new { ID = 1012, PrimaryCategoryID = 502, ProductName = "Prod_12", ProductPrice = 126.0 },
                        new { ID = 1013, PrimaryCategoryID = 503, ProductName = "Prod_13", ProductPrice = 419.0 },
                        new { ID = 1014, PrimaryCategoryID = 504, ProductName = "Prod_14", ProductPrice = 302.0 },
                        new { ID = 1015, PrimaryCategoryID = 500, ProductName = "Prod_15", ProductPrice = 145.0 },
                        new { ID = 1016, PrimaryCategoryID = 501, ProductName = "Prod_16", ProductPrice = 335.0 },
                        new { ID = 1017, PrimaryCategoryID = 502, ProductName = "Prod_17", ProductPrice = 48.0 },
                        new { ID = 1018, PrimaryCategoryID = 503, ProductName = "Prod_18", ProductPrice = 199.0 },
                        new { ID = 1019, PrimaryCategoryID = 504, ProductName = "Prod_19", ProductPrice = 473.0 },
                        new { ID = 1020, PrimaryCategoryID = 500, ProductName = "Prod_20", ProductPrice = 40.0 },
                        new { ID = 1021, PrimaryCategoryID = 501, ProductName = "Prod_21", ProductPrice = 72.0 },
                        new { ID = 1022, PrimaryCategoryID = 502, ProductName = "Prod_22", ProductPrice = 463.0 },
                        new { ID = 1023, PrimaryCategoryID = 503, ProductName = "Prod_23", ProductPrice = 173.0 },
                        new { ID = 1024, PrimaryCategoryID = 504, ProductName = "Prod_24", ProductPrice = 381.0 },
                        new { ID = 1025, PrimaryCategoryID = 500, ProductName = "Prod_25", ProductPrice = 98.0 },
                        new { ID = 1026, PrimaryCategoryID = 501, ProductName = "Prod_26", ProductPrice = 389.0 },
                        new { ID = 1027, PrimaryCategoryID = 502, ProductName = "Prod_27", ProductPrice = 342.0 },
                        new { ID = 1028, PrimaryCategoryID = 503, ProductName = "Prod_28", ProductPrice = 332.0 },
                        new { ID = 1029, PrimaryCategoryID = 504, ProductName = "Prod_29", ProductPrice = 59.0 },
                        new { ID = 1030, PrimaryCategoryID = 500, ProductName = "Prod_30", ProductPrice = 493.0 },
                        new { ID = 1031, PrimaryCategoryID = 501, ProductName = "Prod_31", ProductPrice = 136.0 },
                        new { ID = 1032, PrimaryCategoryID = 502, ProductName = "Prod_32", ProductPrice = 26.0 },
                        new { ID = 1033, PrimaryCategoryID = 503, ProductName = "Prod_33", ProductPrice = 184.0 },
                        new { ID = 1034, PrimaryCategoryID = 504, ProductName = "Prod_34", ProductPrice = 37.0 },
                        new { ID = 1035, PrimaryCategoryID = 500, ProductName = "Prod_35", ProductPrice = 473.0 },
                        new { ID = 1036, PrimaryCategoryID = 501, ProductName = "Prod_36", ProductPrice = 475.0 },
                        new { ID = 1037, PrimaryCategoryID = 502, ProductName = "Prod_37", ProductPrice = 42.0 },
                        new { ID = 1038, PrimaryCategoryID = 503, ProductName = "Prod_38", ProductPrice = 217.0 },
                        new { ID = 1039, PrimaryCategoryID = 504, ProductName = "Prod_39", ProductPrice = 255.0 },
                        new { ID = 1040, PrimaryCategoryID = 500, ProductName = "Prod_40", ProductPrice = 299.0 },
                        new { ID = 1041, PrimaryCategoryID = 501, ProductName = "Prod_41", ProductPrice = 369.0 },
                        new { ID = 1042, PrimaryCategoryID = 502, ProductName = "Prod_42", ProductPrice = 391.0 },
                        new { ID = 1043, PrimaryCategoryID = 503, ProductName = "Prod_43", ProductPrice = 446.0 },
                        new { ID = 1044, PrimaryCategoryID = 504, ProductName = "Prod_44", ProductPrice = 224.0 },
                        new { ID = 1045, PrimaryCategoryID = 500, ProductName = "Prod_45", ProductPrice = 54.0 },
                        new { ID = 1046, PrimaryCategoryID = 501, ProductName = "Prod_46", ProductPrice = 408.0 },
                        new { ID = 1047, PrimaryCategoryID = 502, ProductName = "Prod_47", ProductPrice = 300.0 },
                        new { ID = 1048, PrimaryCategoryID = 503, ProductName = "Prod_48", ProductPrice = 15.0 },
                        new { ID = 1049, PrimaryCategoryID = 504, ProductName = "Prod_49", ProductPrice = 12.0 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.ProductSupplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductID");

                    b.Property<int>("SupplierID");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProductSupplier");

                    b.HasData(
                        new { ID = 18, ProductID = 111, SupplierID = 11 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Purchase", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreditDetails");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<double>("Total");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Purchase");

                    b.HasData(
                        new { ID = 9000, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7000" },
                        new { ID = 9001, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7001" },
                        new { ID = 9002, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7002" },
                        new { ID = 9003, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7003" },
                        new { ID = 9004, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7004" },
                        new { ID = 9005, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7005" },
                        new { ID = 9006, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7006" },
                        new { ID = 9007, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7007" },
                        new { ID = 9008, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7008" },
                        new { ID = 9009, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7009" },
                        new { ID = 9010, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7010" },
                        new { ID = 9011, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7011" },
                        new { ID = 9012, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7012" },
                        new { ID = 9013, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7013" },
                        new { ID = 9014, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7014" },
                        new { ID = 9015, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7015" },
                        new { ID = 9016, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7016" },
                        new { ID = 9017, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7017" },
                        new { ID = 9018, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7018" },
                        new { ID = 9019, CreditDetails = "abc", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "rt_7019" },
                        new { ID = 15, CreditDetails = "YOOOLLLLOOOO", PurchaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Total = 0.0, UserID = "admin_ID_123456789" }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.PurchaseItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("ProductID");

                    b.Property<int>("PurchaseID");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("PurchaseID");

                    b.ToTable("PurchaseItem");

                    b.HasData(
                        new { ID = 90000, Amount = 7, ProductID = 1048, PurchaseID = 9000 },
                        new { ID = 90001, Amount = 6, ProductID = 1037, PurchaseID = 9000 },
                        new { ID = 90002, Amount = 4, ProductID = 1002, PurchaseID = 9000 },
                        new { ID = 90010, Amount = 4, ProductID = 1021, PurchaseID = 9001 },
                        new { ID = 90011, Amount = 9, ProductID = 1021, PurchaseID = 9001 },
                        new { ID = 90012, Amount = 3, ProductID = 1045, PurchaseID = 9001 },
                        new { ID = 90020, Amount = 6, ProductID = 1045, PurchaseID = 9002 },
                        new { ID = 90021, Amount = 3, ProductID = 1004, PurchaseID = 9002 },
                        new { ID = 90022, Amount = 8, ProductID = 1011, PurchaseID = 9002 },
                        new { ID = 90030, Amount = 6, ProductID = 1039, PurchaseID = 9003 },
                        new { ID = 90031, Amount = 6, ProductID = 1016, PurchaseID = 9003 },
                        new { ID = 90032, Amount = 8, ProductID = 1032, PurchaseID = 9003 },
                        new { ID = 90040, Amount = 3, ProductID = 1017, PurchaseID = 9004 },
                        new { ID = 90041, Amount = 1, ProductID = 1017, PurchaseID = 9004 },
                        new { ID = 90042, Amount = 6, ProductID = 1044, PurchaseID = 9004 },
                        new { ID = 90050, Amount = 2, ProductID = 1018, PurchaseID = 9005 },
                        new { ID = 90051, Amount = 6, ProductID = 1033, PurchaseID = 9005 },
                        new { ID = 90052, Amount = 3, ProductID = 1006, PurchaseID = 9005 },
                        new { ID = 90060, Amount = 4, ProductID = 1025, PurchaseID = 9006 },
                        new { ID = 90061, Amount = 6, ProductID = 1015, PurchaseID = 9006 },
                        new { ID = 90062, Amount = 6, ProductID = 1025, PurchaseID = 9006 },
                        new { ID = 90070, Amount = 5, ProductID = 1031, PurchaseID = 9007 },
                        new { ID = 90071, Amount = 3, ProductID = 1029, PurchaseID = 9007 },
                        new { ID = 90072, Amount = 2, ProductID = 1041, PurchaseID = 9007 },
                        new { ID = 90080, Amount = 2, ProductID = 1039, PurchaseID = 9008 },
                        new { ID = 90081, Amount = 9, ProductID = 1043, PurchaseID = 9008 },
                        new { ID = 90082, Amount = 4, ProductID = 1040, PurchaseID = 9008 },
                        new { ID = 90090, Amount = 4, ProductID = 1033, PurchaseID = 9009 },
                        new { ID = 90091, Amount = 8, ProductID = 1003, PurchaseID = 9009 },
                        new { ID = 90092, Amount = 7, ProductID = 1014, PurchaseID = 9009 },
                        new { ID = 90100, Amount = 4, ProductID = 1003, PurchaseID = 9010 },
                        new { ID = 90101, Amount = 7, ProductID = 1023, PurchaseID = 9010 },
                        new { ID = 90102, Amount = 7, ProductID = 1029, PurchaseID = 9010 },
                        new { ID = 90110, Amount = 3, ProductID = 1029, PurchaseID = 9011 },
                        new { ID = 90111, Amount = 8, ProductID = 1022, PurchaseID = 9011 },
                        new { ID = 90112, Amount = 8, ProductID = 1038, PurchaseID = 9011 },
                        new { ID = 90120, Amount = 2, ProductID = 1028, PurchaseID = 9012 },
                        new { ID = 90121, Amount = 7, ProductID = 1006, PurchaseID = 9012 },
                        new { ID = 90122, Amount = 2, ProductID = 1048, PurchaseID = 9012 },
                        new { ID = 90130, Amount = 1, ProductID = 1014, PurchaseID = 9013 },
                        new { ID = 90131, Amount = 2, ProductID = 1025, PurchaseID = 9013 },
                        new { ID = 90132, Amount = 7, ProductID = 1011, PurchaseID = 9013 },
                        new { ID = 90140, Amount = 4, ProductID = 1040, PurchaseID = 9014 },
                        new { ID = 90141, Amount = 3, ProductID = 1018, PurchaseID = 9014 },
                        new { ID = 90142, Amount = 7, ProductID = 1048, PurchaseID = 9014 },
                        new { ID = 90150, Amount = 6, ProductID = 1009, PurchaseID = 9015 },
                        new { ID = 90151, Amount = 6, ProductID = 1004, PurchaseID = 9015 },
                        new { ID = 90152, Amount = 2, ProductID = 1028, PurchaseID = 9015 },
                        new { ID = 90160, Amount = 8, ProductID = 1004, PurchaseID = 9016 },
                        new { ID = 90161, Amount = 8, ProductID = 1043, PurchaseID = 9016 },
                        new { ID = 90162, Amount = 6, ProductID = 1036, PurchaseID = 9016 },
                        new { ID = 90170, Amount = 9, ProductID = 1037, PurchaseID = 9017 },
                        new { ID = 90171, Amount = 1, ProductID = 1020, PurchaseID = 9017 },
                        new { ID = 90172, Amount = 7, ProductID = 1017, PurchaseID = 9017 },
                        new { ID = 90180, Amount = 9, ProductID = 1011, PurchaseID = 9018 },
                        new { ID = 90181, Amount = 8, ProductID = 1020, PurchaseID = 9018 },
                        new { ID = 90182, Amount = 3, ProductID = 1028, PurchaseID = 9018 },
                        new { ID = 90190, Amount = 9, ProductID = 1010, PurchaseID = 9019 },
                        new { ID = 90191, Amount = 7, ProductID = 1008, PurchaseID = 9019 },
                        new { ID = 90192, Amount = 2, ProductID = 1048, PurchaseID = 9019 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Rating", b =>
                {
                    b.Property<int>("ProductID");

                    b.Property<string>("UserID");

                    b.Property<int>("ID");

                    b.Property<int>("ProductRating");

                    b.HasKey("ProductID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("Rating");

                    b.HasData(
                        new { ProductID = 1007, UserID = "rt_7000", ID = 7000, ProductRating = 1 },
                        new { ProductID = 1007, UserID = "rt_7001", ID = 7001, ProductRating = 2 },
                        new { ProductID = 1007, UserID = "rt_7002", ID = 7002, ProductRating = 3 },
                        new { ProductID = 1007, UserID = "rt_7003", ID = 7003, ProductRating = 4 },
                        new { ProductID = 1007, UserID = "rt_7004", ID = 7004, ProductRating = 5 },
                        new { ProductID = 1007, UserID = "rt_7005", ID = 7005, ProductRating = 1 },
                        new { ProductID = 1007, UserID = "rt_7006", ID = 7006, ProductRating = 2 },
                        new { ProductID = 1007, UserID = "rt_7007", ID = 7007, ProductRating = 3 },
                        new { ProductID = 1007, UserID = "rt_7008", ID = 7008, ProductRating = 4 },
                        new { ProductID = 1007, UserID = "rt_7009", ID = 7009, ProductRating = 5 },
                        new { ProductID = 1007, UserID = "rt_7010", ID = 7010, ProductRating = 1 },
                        new { ProductID = 1007, UserID = "rt_7011", ID = 7011, ProductRating = 2 },
                        new { ProductID = 1007, UserID = "rt_7012", ID = 7012, ProductRating = 3 },
                        new { ProductID = 1007, UserID = "rt_7013", ID = 7013, ProductRating = 4 },
                        new { ProductID = 1007, UserID = "rt_7014", ID = 7014, ProductRating = 5 },
                        new { ProductID = 1007, UserID = "rt_7015", ID = 7015, ProductRating = 1 },
                        new { ProductID = 1007, UserID = "rt_7016", ID = 7016, ProductRating = 2 },
                        new { ProductID = 1007, UserID = "rt_7017", ID = 7017, ProductRating = 3 },
                        new { ProductID = 1007, UserID = "rt_7018", ID = 7018, ProductRating = 4 },
                        new { ProductID = 1007, UserID = "rt_7019", ID = 7019, ProductRating = 5 },
                        new { ProductID = 111, UserID = "admin_ID_123456789", ID = 16, ProductRating = 1 }
                    );
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Supplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Contact");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Website");

                    b.HasKey("ID");

                    b.ToTable("Supplier");

                    b.HasData(
                        new { ID = 11, Address = "lilach 99", Contact = "gil", Email = "gil@ziv.com", Name = "Guro", Phone = "054-9999999", Website = "www.anshubi.com" },
                        new { ID = 12, Address = "Aviv 99", Contact = "Zil", Email = "Ziv@Giv.com", Name = "Theuro", Phone = "054-9999199", Website = "www.tuna.com" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Cart", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("OtoSpaMVC.Models.CartItem", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Product", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Category", "PrimaryCategory")
                        .WithMany()
                        .HasForeignKey("PrimaryCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OtoSpaMVC.Models.ProductSupplier", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Purchase", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.ApplicationUser", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("OtoSpaMVC.Models.PurchaseItem", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OtoSpaMVC.Models.Rating", b =>
                {
                    b.HasOne("OtoSpaMVC.Models.Product", "Product")
                        .WithMany("ProductRatings")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OtoSpaMVC.Models.ApplicationUser", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
